name: Publish Document
on:
    push:
        branches:
            - main
        workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.x # install python

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pygments==2.17.2 pymdown-extensions
                  pip install mkdocs-exclude
                  pip install mkdocs-material==9.6.8
                  pip install jieba==0.42.1   # 安装依赖
                  pip install mkdocs-swagger-ui-tag

            - name: Build the document
              run: mkdocs build

            - name: Add CNAME file
              run: echo 'docs.gasfree.io' > site/CNAME

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.TOKEN}}
                  branch: gh-pages
                  folder: site
